require("plugins")
require('keybindings')
require("options")
require('lualine-config')
require('bufferline-config')
require('nvim-tree-config')
require("treesitter-config")
require('ts-autotag-config')
require('autopairs-config')
require('whichkey-config')
require('cmp-config')
require('telescope-config')
vim.cmd.colorscheme "catppuccin-mocha"
